### ISSUE TITLE
Read/Write

### ISSUE THREAD

**Issue by asegurpe** [thomasX/nfc-util#1]
Hi friend,

Firstly I must congratulate you for this project, it's all that I need.

But, I have some problems for customize it, for example, I cannot write and recover after any value.

Can you help me?

Thanks!!!

**Comment by thomasX** [comment]
can you give me more details ?

**Comment by asegurpe** [comment]
I use the write method of NFCWriter as your example:

writer.write("Hello World!");

But when I use read for recover this, I never view the value:

{identity=04737BD55681, value=}

I belive that the result would be similar to:

{identity=04737BD55681, value=Hello World!}

Do I say the truth?

**Comment by asegurpe** [comment]
The code is next:

`private void readCard(NFCReader reader) {`
`		try {`
`			Properties card = reader.read();`
`			System.out.println(card.toString());`
`			String tagID = (String) card.get(NFCReader.PROPERTY_TYPE_TAG_IDENTITY);`
`			String tagValue = (String) card.get(NFCReader.PROPERTY_TYPE_TAG_VALUE);`
`			if (!card.equals(this.tagContent)) {`
`				this.tagContent = card;`
`				System.out.println(new Date().toString() + " .... tag wurde gelesen:");`
`				if (!this.noSound) {`
`					// playOK();`
`				}`
`				String result = "{ id: '" + tagID + "',content: '" + tagValue + "' }";`
`				System.out.println(result);`
`				try {`
`					this.writer.write("Hello world!");`
`					delay(300);`
`				} catch (NFCException | CardException e) {`
`					// TODO Auto-generated catch block`
`					e.printStackTrace();`
`				}`
`			}`
`		} catch (Exception e) {`
`			// TODO: handle exception`
`			this.tagContent = new Properties();`
`			if (e instanceof javax.smartcardio.CardNotPresentException) {`
`				System.out.println("Card not present");`
`			} else {`
`				e.printStackTrace();`
`			}`
`		}`
`	}`

And it's into the while loop.

**Comment by thomasX** [comment]
just have a look at the demo-applet ! 
https://github.com/thomasX/nfc-util/blob/master/NFC_UTIL/src/main/java/info/margreiter/nfc/applet/NFCReaderApplet.java

this works fine !

**Comment by asegurpe** [comment]
My code is a copy of your code adding the write "Hello world!" into nfc card, but your example only read content, never write.

Can you help me?

**Comment by thomasX** [comment]
just have a look at https://github.com/thomasX/nfc-util/blob/master/NFC_UTIL/src/test/java/info/margreiter/nfc/mifareUltralightC/NFCReaderTest.java
`@Test
	public void testRead(){
		
		String testString = "0300@06<40005000";
		
		NFCReader reader = new NFCReader();
		Properties result= new Properties();
		try {
			new NFCWriter().write(testString);
			result = reader.read();
		} catch (InvalidKeyException e) {
			// TODO Auto-generated catch block
.........
.........
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		assertNotNull(result.get(NFCReader.PROPERTY_TYPE_TAG_VALUE));
		assertEquals(testString, result.get(NFCReader.PROPERTY_TYPE_TAG_VALUE));
	}`


... here you see how to write and read the tag ! 
Attention ! 
You can'T write to the tag if you have previously locked the tag. 
Keep in mind: locking a tag cannot be undone !
... maybe this is your problem

**Comment by asegurpe** [comment]
With NFC Tools Android application I've see string "Hello world!" writed using your test.

![screenshot_20180420-115148](https://user-images.githubusercontent.com/936816/39044819-89ceb58c-4491-11e8-89f4-a57aecad7d1c.png)

But now, at the moment to read, cannot recover this string and test failed.
The string recovered is "".

Thanks!!
